#!/bin/sh
id=`awk 'BEGIN{srand();printf("%d", 65536*rand())}'`
workspace=$(swaymsg -t get_workspaces | grep -B 4 "focused\": true" | grep -m 1 -o "[0-9]")

swaymsg mark add $id
swaymsg move scratchpad

echo "$1 \"$2\"" | sh

swaymsg \[con_mark="$id"\] move workspace $workspace
swaymsg \[con_mark="$id"\] floating toggle
