#!/bin/sh
id=$RANDOM
swaymsg mark add $id

swaymsg \[con_mark="$id"\] layout stacking &

"$@" &

swaymsg for_window [title=.*] split vertical

wait

swaymsg \[con_mark="$id"\] layout default
swaymsg \[con_mark="$id"\] mark remove $id
